[workspace]

members = [
    "neptune_core",
    "neptune_vulkan",
    "neptune_editor", "neptune_convert",
]

# Force rapier3d to always build with optimization
[profile.dev.package.rapier3d]
opt-level = 3
