[package]
name = "neptune_editor"
version = "0.1.0"
authors = ["Joshua_Masci <iamshortman@gmail.com>"]
edition = "2021"

[build-dependencies]
shaderc = "0.8.0"

[dependencies]
winit = "0.26"
neptune_core = { path = "../neptune_core"}
neptune_graphics = { path = "../neptune_graphics"}

imgui = { git = "https://github.com/imgui-rs/imgui-rs", features = ["docking"] }
imgui-winit-support = { git = "https://github.com/imgui-rs/imgui-rs" }

image = "0.24.2"
bytemuck = "1.12.0"