[package]
name = "neptune_editor"
version = "0.1.0"
authors = ["Joshua_Masci <iamshortman@gmail.com>"]
edition = "2021"

[dependencies]
winit = "0.26"
neptune_core = { path = "../neptune_core"}
neptune_graphics = { path = "../neptune_graphics"}
