[package]
name = "neptune_editor"
version = "0.1.0"
authors = ["Joshua_Masci <iamshortman@gmail.com>"]
edition = "2021"

[build-dependencies]
shaderc = "0.8.0"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"

winit = "0.27.4"
neptune_core = { path = "../neptune_core"}
neptune_vulkan = { path = "../neptune_vulkan" }
neptune_vulkan_macro = { path = "../neptune_vulkan_macro" }

image = "0.24.2"
