[package]
name = "neptune_editor"
version = "0.1.0"
authors = ["Joshua_Masci <iamshortman@gmail.com>"]
edition = "2021"

[dependencies]
neptune_core = { path = "../neptune_core"}
winit = "0.26"
wgpu = "0.13.1"
env_logger = "0.9"
pollster = "0.2"
bytemuck = { version = "1.9", features = ["derive"] }
glam = { version = "0.21", features = ["serde", "bytemuck"] }
image = "0.24.2"