[package]
name = "neptune_vulkan_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"
darling = "0.14.2"

neptune_vulkan = { path = "../neptune_vulkan" }