[package]
name = "neptune_graphics"
version = "0.1.0"
authors = ["Joshua_Masci <iamshortman@gmail.com>"]
edition = "2021"

[dependencies]
thiserror = "1.0"
bitflags = "1.3.2"
raw-window-handle = "0.5.0"

[features]
