[package]
name = "neptune_graphics"
version = "0.1.0"
authors = ["Joshua_Masci <iamshortman@gmail.com>"]
edition = "2021"

[dependencies]
bitflags = "1.3.2"
raw-window-handle = "0.5.0"

ash = "0.37.0"
ash-window = "0.12.0"
gpu-allocator = "0.19.1"

[features]
